# Generated by Django 4.2.9 on 2024-01-30 02:27

# Django Imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=253)),
                ("is_active", models.BooleanField(default=True)),
                ("is_starred", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "A"),
                            (1, "AAAA"),
                            (2, "CNAME"),
                            (3, "MX"),
                            (4, "NS"),
                            (5, "PTR"),
                            (6, "TXT"),
                        ]
                    ),
                ),
                ("name", models.CharField(max_length=63)),
                ("value", models.CharField(max_length=255)),
                ("observation", models.TextField(blank=True, null=True)),
                (
                    "website",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="dnsmanager.website",
                    ),
                ),
            ],
        ),
    ]
